INSERT INTO menu_items (name, description, price, category, image_url, available, tenant_id)
VALUES
('Chicken Biryani', 'Aromatic basmati rice with spicy chicken', 180.00, 'Biryani', 'https://postimg.cc/9rPTL1J1', true, NULL),
('Paneer Tikka', 'Grilled paneer cubes with spices', 160.00, 'Starter', 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80', true, NULL),
('Mutton Korma', 'Rich mutton curry with house spices', 260.00, 'Main Course', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', false, NULL),
('Veg Fried Rice', 'Wok tossed rice with vegetables', 140.00, 'Rice', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80', true, NULL),
('Veg Dum Biryani', 'Classic vegetarian biryani with aromatic spices', 100.00, 'Biryani', '', true, NULL),
('Ch. Dum Biryani', 'Chicken dum biryani, slow-cooked for rich flavor', 115.00, 'Biryani', '', true, NULL),
('Ch. Tandoor Biryani', 'Tandoori chicken biryani with a smoky aroma', 125.00, 'Biryani', '', true, NULL),
('Ch. Hyderabadi Biryani', 'Hyderabadi style chicken biryani', 125.00, 'Biryani', '', true, NULL),
('Maska Biryani', 'Biryani with a buttery twist', 125.00, 'Biryani', '', true, NULL),
('Chicken Sukkha (Full)', 'Dry chicken preparation with spices', 279.00, 'Main Course (Non Veg)', '', true, NULL),
('Chicken Handi (Half)', 'Chicken handi, half portion', 179.00, 'Main Course (Non Veg)', '', true, NULL),
('Chicken Handi (Full)', 'Chicken handi, full portion', 279.00, 'Main Course (Non Veg)', '', true, NULL),
('Chicken Masala (Half)', 'Chicken masala, half portion', 169.00, 'Main Course (Non Veg)', '', true, NULL),
('Chicken Masala (Full)', 'Chicken masala, full portion', 269.00, 'Main Course (Non Veg)', '', true, NULL),
('Chicken Korma (Half)', 'Chicken korma, half portion', 179.00, 'Main Course (Non Veg)', '', true, NULL),
('Chicken Korma (Full)', 'Chicken korma, full portion', 279.00, 'Main Course (Non Veg)', '', true, NULL),
('Chicken Tikka Masala (Half)', 'Chicken tikka masala, half portion', 189.00, 'Main Course (Non Veg)', '', true, NULL),
('Chicken Tikka Masala (Full)', 'Chicken tikka masala, full portion', 299.00, 'Main Course (Non Veg)', '', true, NULL),
('Paneer Masala (Half)', 'Paneer masala, half portion', 169.00, 'Main Course (Veg)', '', true, NULL),
('Paneer Masala (Full)', 'Paneer masala, full portion', 269.00, 'Main Course (Veg)', '', true, NULL),
('Paneer Handi (Half)', 'Paneer handi, half portion', 179.00, 'Main Course (Veg)', '', true, NULL),
('Paneer Handi (Full)', 'Paneer handi, full portion', 279.00, 'Main Course (Veg)', '', true, NULL),
('Paneer Korma (Half)', 'Paneer korma, half portion', 179.00, 'Main Course (Veg)', '', true, NULL),
('Paneer Korma (Full)', 'Paneer korma, full portion', 279.00, 'Main Course (Veg)', '', true, NULL),
('Dal Tadka', 'Yellow dal with tadka', 130.00, 'Main Course (Veg)', '', true, NULL),
('Egg Curry (Half)', 'Egg curry, half portion', 100.00, 'Main Course (Veg)', '', true, NULL),
('Egg Curry (Full)', 'Egg curry, full portion', 180.00, 'Main Course (Veg)', '', true, NULL),
('Al Faham Normal (Q)', 'Quarter portion of classic grilled chicken', 139.00, 'Starters', '', true, NULL),
('Al Faham Normal (H)', 'Half portion of classic grilled chicken', 249.00, 'Starters', '', true, NULL),
('Al Faham Normal (F)', 'Full portion of classic grilled chicken', 469.00, 'Starters', '', true, NULL),
('Al Faham Peri Peri (Q)', 'Quarter portion of spicy peri peri grilled chicken', 149.00, 'Starters', '', true, NULL),
('Al Faham Peri Peri (H)', 'Half portion of spicy peri peri grilled chicken', 259.00, 'Starters', '', true, NULL),
('Al Faham Peri Peri (F)', 'Full portion of spicy peri peri grilled chicken', 479.00, 'Starters', '', true, NULL),
('Ch. Tikka (6)', '6 pieces of chicken tikka', 169.00, 'Starters', '', true, NULL),
('Ch. Dry Lollypop (H4)', '4 pieces of dry chicken lollypop', 119.00, 'Starters', '', true, NULL),
('Ch. Dry Lollypop (F6)', '6 pieces of dry chicken lollypop', 169.00, 'Starters', '', true, NULL),
('Ch. Cryspy Lollypop (H4)', '4 pieces of crispy chicken lollypop', 129.00, 'Starters', '', true, NULL),
('Ch. Cryspy Lollypop (F6)', '6 pieces of crispy chicken lollypop', 179.00, 'Starters', '', true, NULL),
('Ch. Wings (6)', '6 pieces of chicken wings', 169.00, 'Starters', '', true, NULL),
('Ch. Drumstick (H2)', '2 pieces of chicken drumstick', 149.00, 'Starters', '', true, NULL),
('Ch. Drumstick (F4)', '4 pieces of chicken drumstick', 269.00, 'Starters', '', true, NULL),
('Ch. Seek Kabab', 'Chicken seekh kabab', 119.00, 'Starters', '', true, NULL),
('Paneer Tikka (6)', '6 pieces of paneer tikka', 169.00, 'Starters', '', true, NULL),
('Ch. Tikka Small (3)', '3 pieces of small chicken tikka', 100.00, 'Starters', '', true, NULL),
('Egg Roll', 'Egg roll', 79.00, 'Rolls', '', true, NULL),
('Chicken Roll', 'Chicken roll', 139.00, 'Rolls', '', true, NULL),
('Ch. Malai Tikka Roll', 'Malai tikka chicken roll', 149.00, 'Rolls', '', true, NULL),
('Ch. Tikka Roll', 'Chicken tikka roll', 149.00, 'Rolls', '', true, NULL),
('Ch. Egg Combo Roll', 'Chicken and egg combo roll', 179.00, 'Rolls', '', true, NULL),
('Omlette Pao', 'Omelette served with 2 eggs and 2 pao', 55.00, 'Breakfast', '', true, NULL),
('Omlette (2 Eggs)', 'Plain omelette made with 2 eggs', 45.00, 'Breakfast', '', true, NULL),
('Boilled Eggs (2 Eggs)', '2 boiled eggs', 30.00, 'Breakfast', '', true, NULL),
('Pao (1p)', 'Single piece of pao bread', 6.00, 'Breakfast', '', true, NULL),
('Butter Pao (1p)', 'Single piece of pao bread with butter', 10.00, 'Breakfast', '', true, NULL),
('Bun Maska', 'Soft bun with butter', 35.00, 'Breakfast', '', true, NULL),
('Egg Bhurji (2 Eggs)', 'Spiced scrambled eggs (2 eggs)', 45.00, 'Breakfast', '', true, NULL),
('Sandwich', 'Simple breakfast sandwich', 45.00, 'Breakfast', '', true, NULL),
('Cheese Omlette', 'Cheese omelette', 55.00, 'Breakfast', '', true, NULL),
('Chai (Small)', 'Small cup of chai', 15.00, 'Beverages', '', true, NULL),
('Chai (Large)', 'Large cup of chai', 30.00, 'Beverages', '', true, NULL),
('Sp. Chai', 'Special chai', 20.00, 'Beverages', '', true, NULL),
('Coffee (Small)', 'Small cup of coffee', 25.00, 'Beverages', '', true, NULL),
('Coffee (Large)', 'Large cup of coffee', 50.00, 'Beverages', '', true, NULL),
('Black Coffee (Small)', 'Small cup of black coffee', 25.00, 'Beverages', '', true, NULL),
('Black Coffee (Large)', 'Large cup of black coffee', 50.00, 'Beverages', '', true, NULL),
('Green Tea', 'Green tea', 25.00, 'Beverages', '', true, NULL),
('Water 500 ml', 'Packaged water 500ml', 10.00, 'Beverages', '', true, NULL),
('Water 1ltr', 'Packaged water 1 litre', 20.00, 'Beverages', '', true, NULL),
('Lime Soda', 'Lime soda', 30.00, 'Beverages', '', true, NULL),
('Lemon Tea', 'Lemon tea', 25.00, 'Beverages', '', true, NULL),
('Mojito', 'Refreshing mojito', 99.00, 'Beverages', '', true, NULL);

INSERT INTO restaurant_settings (id, restaurant_name, payment_qr_image_url, contact_number)
VALUES (1, 'Dizminu', 'https://dummyimage.com/320x320/111/fff&text=Scan+QR+to+Pay', '+91-9999999999');
